user:
  email:
    regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+/
  password:
    min_length: 4
  user_url: "https://secure.gravatar.com/avatar/#{gravatar_id}"
  gravatar_url: "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  intro_log_up: "Sign up now!"



digits:
  length_4: 4
  length_30: 30
  size_80: 80
  expired_2: 2

micropost:
  image_max_5MB: 5
  image_200: 200

valid_image_format: "image/jpeg,image/gif,image/png"
info_image: "230d3040650cb452ed1d.jpg"
width_200: "200px"
