user:
  email:
    regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+/
  password:
    min_length: 8
  user_url: "https://secure.gravatar.com/avatar/#{gravatar_id}"
  intro_log_up: "Sign up now!"

digits:
  length_10: 10
  length_30: 30
